// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

fun add(a: SageVal, b: SageVal): SageVal {
    return S.add(a, b)
    return S.nil
}

fun factorial(n: SageVal): SageVal {
    if (S.truthy(S.lte(n, S.num(1.0)))) {
        return S.num(1.0)
    }
    return S.mul(n, factorial(S.sub(n, S.num(1.0))))
    return S.nil
}

fun fibonacci(n: SageVal): SageVal {
    if (S.truthy(S.lte(n, S.num(0.0)))) {
        return S.num(0.0)
    }
    if (S.truthy(S.eq(n, S.num(1.0)))) {
        return S.num(1.0)
    }
    return S.add(fibonacci(S.sub(n, S.num(1.0))), fibonacci(S.sub(n, S.num(2.0))))
    return S.nil
}

fun classify(n: SageVal): SageVal {
    if (S.truthy(S.gt(n, S.num(0.0)))) {
        return S.str("positive")
    }
    if (S.truthy(S.lt(n, S.num(0.0)))) {
        return S.str("negative")
    }
    return S.str("zero")
    return S.nil
}

fun sum_to(n: SageVal): SageVal {
    var total = S.num(0.0)
    var i = S.num(1.0)
    while (S.truthy(S.lte(i, n))) {
        total = S.add(total, i)
        i = S.add(i, S.num(1.0))
    }
    return total
    return S.nil
}

fun find_first_even(items: SageVal): SageVal {
    run {
        val _iter_1 = S.toIterable(items)
        for (item in _iter_1) {
            if (S.truthy(S.eq(S.mod(item, S.num(2.0)), S.num(0.0)))) {
                return item
            }
        }
    }
    return S.nil
    return S.nil
}

fun main() {
    S.init()
    
    S.printLn(add(S.num(10.0), S.num(20.0)))
    S.printLn(factorial(S.num(5.0)))
    S.printLn(fibonacci(S.num(10.0)))
    S.printLn(classify(S.num(42.0)))
    S.printLn(classify(S.sub(S.num(0.0), S.num(7.0))))
    S.printLn(classify(S.num(0.0)))
    S.printLn(sum_to(S.num(100.0)))
    S.printLn(find_first_even(S.array(S.num(1.0), S.num(3.0), S.num(5.0), S.num(4.0), S.num(7.0))))
    S.printLn(find_first_even(S.array(S.num(1.0), S.num(3.0), S.num(5.0), S.num(7.0))))
    
}
