// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

var greeting: S.Value = S.nil
var d: S.Value = S.nil
var c: S.Value = S.nil
var b: S.Value = S.nil
var a: S.Value = S.nil
var nothing: S.Value = S.nil
var flag: S.Value = S.nil
var name: S.Value = S.nil
var x: S.Value = S.nil

fun main() {
    S.init()
    
    x = S.num(10.0)
    name = S.str("Sage")
    flag = S.bool(true)
    nothing = S.nil
    S.printLn(x)
    S.printLn(name)
    S.printLn(flag)
    S.printLn(nothing)
    a = S.add(S.num(10.0), S.num(20.0))
    b = S.mul(a, S.num(3.0))
    c = S.div(b, S.num(2.0))
    d = S.mod(S.num(100.0), S.num(7.0))
    S.printLn(a)
    S.printLn(b)
    S.printLn(c)
    S.printLn(d)
    greeting = S.add(S.add(S.str("Hello, "), name), S.str("!"))
    S.printLn(greeting)
    S.printLn(S.len(greeting))
    S.printLn(S.gt(S.num(10.0), S.num(5.0)))
    S.printLn(S.eq(S.num(10.0), S.num(10.0)))
    S.printLn(S.neq(S.num(10.0), S.num(5.0)))
    S.printLn(S.lte(S.num(10.0), S.num(10.0)))
    S.printLn(S.and(S.bool(true), S.bool(false)))
    S.printLn(S.or(S.bool(true), S.bool(false)))
    S.printLn(S.not(S.bool(false)))
    S.printLn(S.str(S.num(42.0)))
    S.printLn(S.toNumber(S.str("3.14")))
    S.printLn(S.typeOf(S.num(42.0)))
    S.printLn(S.typeOf(S.str("hello")))
    
}
