# SageLang assembly output for x86_64
# Profile: hosted
# Generated by sage compiler

.text
.globl main

main:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
  # v0 = string
  leaq .LC0(%rip), %rdi
  call sage_rt_string
  movq %rax, -16(%rbp)
  movq %rdx, -8(%rbp)
  # store global 'item' = v0
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  movq -16(%rbp), %rdx
  movq -8(%rbp), %rcx
  call sage_rt_set_global
  # v1 = number 0.000000
  movsd .LN0(%rip), %xmm0
  call sage_rt_number
  movq %rax, -32(%rbp)
  movq %rdx, -24(%rbp)
  # store global 'total' = v1
  leaq sage_globals(%rip), %rdi
  leaq .LC2(%rip), %rsi
  movq -32(%rbp), %rdx
  movq -24(%rbp), %rcx
  call sage_rt_set_global
  # unhandled vinst 31
  # v3 = number 1.000000
  movsd .LN1(%rip), %xmm0
  call sage_rt_number
  movq %rax, -64(%rbp)
  movq %rdx, -56(%rbp)
  # unhandled vinst 32
  # v4 = number 2.000000
  movsd .LN2(%rip), %xmm0
  call sage_rt_number
  movq %rax, -80(%rbp)
  movq %rdx, -72(%rbp)
  # unhandled vinst 32
  # v5 = number 3.000000
  movsd .LN3(%rip), %xmm0
  call sage_rt_number
  movq %rax, -96(%rbp)
  movq %rdx, -88(%rbp)
  # unhandled vinst 32
  # call builtin len
  movq -48(%rbp), %rdi
  movq -40(%rbp), %rsi
  call len
  movq %rax, -112(%rbp)
  movq %rdx, -104(%rbp)
  # v7 = number 0.000000
  movsd .LN-1(%rip), %xmm0
  call sage_rt_number
  movq %rax, -128(%rbp)
  movq %rdx, -120(%rbp)
  # store global '__for_idx__' = v7
  leaq sage_globals(%rip), %rdi
  leaq .LC3(%rip), %rsi
  movq -128(%rbp), %rdx
  movq -120(%rbp), %rcx
  call sage_rt_set_global
  jmp .L0
.L0:
  # v8 = load global '__for_idx__'
  leaq sage_globals(%rip), %rdi
  leaq .LC3(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -144(%rbp)
  movq %rdx, -136(%rbp)
  # v9 = v8 cmp v6
  movq -144(%rbp), %rdi
  movq -136(%rbp), %rsi
  movq -112(%rbp), %rdx
  movq -104(%rbp), %rcx
  call sage_rt_lt
  movq %rax, -160(%rbp)
  movq %rdx, -152(%rbp)
  # branch v9 ? .L1 : .L2
  movl -160(%rbp), %eax
  movq -160(%rbp), %rdi
  movq -152(%rbp), %rsi
  call sage_rt_get_bool
  testl %eax, %eax
  jne .L1
  jmp .L2
.L1:
  # unhandled vinst 33
  # store global 'item' = v10
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  movq -176(%rbp), %rdx
  movq -168(%rbp), %rcx
  call sage_rt_set_global
  # v11 = nil
  call sage_rt_nil
  movq %rax, -192(%rbp)
  movq %rdx, -184(%rbp)
  # v12 = load global 'total'
  leaq sage_globals(%rip), %rdi
  leaq .LC2(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -208(%rbp)
  movq %rdx, -200(%rbp)
  # v13 = load global 'item'
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -224(%rbp)
  movq %rdx, -216(%rbp)
  # v14 = v12 op v13
  movq -208(%rbp), %rdi
  movq -200(%rbp), %rsi
  movq -224(%rbp), %rdx
  movq -216(%rbp), %rcx
  call sage_rt_add
  movq %rax, -240(%rbp)
  movq %rdx, -232(%rbp)
  # v15 = string
  leaq .LC-1(%rip), %rdi
  call sage_rt_string
  movq %rax, -256(%rbp)
  movq %rdx, -248(%rbp)
  # call builtin dict_set
  movq -192(%rbp), %rdi
  movq -184(%rbp), %rsi
  call dict_set
  movq %rax, -272(%rbp)
  movq %rdx, -264(%rbp)
  # v17 = number 1.000000
  movsd .LN-1(%rip), %xmm0
  call sage_rt_number
  movq %rax, -288(%rbp)
  movq %rdx, -280(%rbp)
  # v18 = v8 op v17
  movq -144(%rbp), %rdi
  movq -136(%rbp), %rsi
  movq -288(%rbp), %rdx
  movq -280(%rbp), %rcx
  call sage_rt_add
  movq %rax, -304(%rbp)
  movq %rdx, -296(%rbp)
  # store global '__for_idx__' = v18
  leaq sage_globals(%rip), %rdi
  leaq .LC3(%rip), %rsi
  movq -304(%rbp), %rdx
  movq -296(%rbp), %rcx
  call sage_rt_set_global
  jmp .L0
.L2:
  # v19 = load global 'total'
  leaq sage_globals(%rip), %rdi
  leaq .LC2(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -320(%rbp)
  movq %rdx, -312(%rbp)
  # print v19
  movq -320(%rbp), %rdi
  movq -312(%rbp), %rsi
  call sage_rt_print
  # v20 = load global 'item'
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  call sage_rt_get_global
  movq %rax, -336(%rbp)
  movq %rdx, -328(%rbp)
  # print v20
  movq -336(%rbp), %rdi
  movq -328(%rbp), %rsi
  call sage_rt_print
  xorl %eax, %eax
  leave
  ret

.section .rodata
.LC0:
  .asciz "outer"
.LC1:
  .asciz "item"
.LC2:
  .asciz "total"
.LC3:
  .asciz "__for_idx__"
.LN0:
  .double 0.000000
.LN1:
  .double 1.000000
.LN2:
  .double 2.000000
.LN3:
  .double 3.000000
