/* Minimal bare-metal kernel — generated by Sage */
void serial_init(void);
void serial_putchar(char c);
void serial_puts(const char *s);

void kmain(void) {
    serial_init();
    serial_puts("Hello from SageOS!\r\n");
    while (1) {
        __asm__ volatile("hlt");
    }
}
