#!/usr/bin/env python3
"""Convert .config (kconfig output) to Makefile-includable sage_config.mk"""

import sys
import os

config_file = sys.argv[1] if len(sys.argv) > 1 else ".config"
output_file = sys.argv[2] if len(sys.argv) > 2 else "sage_config.mk"

if not os.path.exists(config_file):
    print(f"No {config_file} found. Run 'make menuconfig' first.", file=sys.stderr)
    sys.exit(0)  # Not an error - just use defaults

config = {}
with open(config_file) as f:
    for line in f:
        line = line.strip()
        if line.startswith("#") or not line:
            continue
        if "=" in line:
            key, val = line.split("=", 1)
            config[key] = val.strip('"')

lines = []
lines.append("# Auto-generated by make menuconfig - do not edit")
lines.append("# Regenerate with: make menuconfig")
lines.append("")

# Compiler
if config.get("CONFIG_CC_CLANG") == "y":
    lines.append("CC = clang")
elif config.get("CONFIG_CC_SYSTEM") == "y":
    lines.append("CC = cc")
else:
    lines.append("CC = gcc")

# Optimization
for opt in ["O0", "O1", "O2", "O3"]:
    if config.get(f"CONFIG_OPT_{opt}") == "y":
        lines.append(f'SAGE_OPT = -{opt}')
        break

# Debug
if config.get("CONFIG_DEBUG") == "y":
    lines.append("DEBUG = 1")

# Vulkan
if config.get("CONFIG_VULKAN") == "y":
    lines.append("VULKAN = 1")
elif config.get("CONFIG_VULKAN", "y") != "y":
    lines.append("VULKAN = 0")

# Pico
if config.get("CONFIG_PICO_BUILD") == "y":
    lines.append("PICO_BUILD = 1")
    board = config.get("CONFIG_PICO_BOARD", "pico")
    lines.append(f"PICO_BOARD = {board}")
    sdk = config.get("CONFIG_PICO_SDK_PATH", "")
    if sdk:
        lines.append(f"PICO_SDK_PATH = {sdk}")

# Install prefix
prefix = config.get("CONFIG_INSTALL_PREFIX", "/usr/local")
if prefix != "/usr/local":
    lines.append(f"PREFIX = {prefix}")

# Self-hosted
if config.get("CONFIG_SELFHOST") == "y":
    lines.append("BUILD_SAGE = ON")
    if config.get("CONFIG_SELFHOST_RUN_TESTS") == "y":
        lines.append("SELFHOST_TESTS = 1")

# LLVM Backend
if config.get("CONFIG_LLVM_BACKEND") != "y":
    lines.append("LLVM_BACKEND = 0")
if config.get("CONFIG_LLVM_RUNTIME") != "y":
    lines.append("LLVM_RUNTIME = 0")

# Native codegen
if config.get("CONFIG_NATIVE_CODEGEN") != "y":
    lines.append("NATIVE_CODEGEN = 0")
else:
    for arch in ["X86_64", "AARCH64", "RV64"]:
        if config.get(f"CONFIG_NATIVE_TARGET_{arch}") == "y":
            lines.append(f"DEFAULT_TARGET = {arch.lower()}")
            break

# Verbose
if config.get("CONFIG_VERBOSE_BUILD") == "y":
    lines.append("V = 1")

with open(output_file, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {output_file}")
"""
Config options available:
  CONFIG_CC_GCC, CONFIG_CC_CLANG, CONFIG_CC_SYSTEM
  CONFIG_BUILD_MAKE, CONFIG_BUILD_CMAKE
  CONFIG_OPT_O0, CONFIG_OPT_O1, CONFIG_OPT_O2, CONFIG_OPT_O3
  CONFIG_DEBUG
  CONFIG_VULKAN, CONFIG_GLFW
  CONFIG_GPU_PLATFORM_AUTO, CONFIG_GPU_PLATFORM_X11, CONFIG_GPU_PLATFORM_WAYLAND
  CONFIG_COMPILE_SHADERS
  CONFIG_CURL, CONFIG_OPENSSL
  CONFIG_PICO_BUILD, CONFIG_PICO_BOARD, CONFIG_PICO_SDK_PATH
  CONFIG_TARGET_HOST, CONFIG_TARGET_X86_64, CONFIG_TARGET_AARCH64, CONFIG_TARGET_RV64
  CONFIG_RUN_TESTS, CONFIG_TEST_INTERPRETER, CONFIG_TEST_SELFHOST, CONFIG_TEST_GPU
  CONFIG_INSTALL_PREFIX, CONFIG_INSTALL_LIBS, CONFIG_INSTALL_LSP
  CONFIG_THREADING, CONFIG_GC_ENABLED, CONFIG_LLVM_RUNTIME, CONFIG_VERBOSE_BUILD
"""
