// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

open class Circle : Shape() {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun `init`(radius: SageVal = S.nil): SageVal {
        super.sageInit(S.str("circle"))
        S.setProperty(S.Value.Obj(this), "radius", radius)
        return S.nil
    }
    
    open fun describe(): SageVal {
        return S.add(S.add(super.describe(), S.str(" r=")), S.str(S.getProperty(S.Value.Obj(this), "radius")))
        return S.nil
    }
    
    open fun area(): SageVal {
        return S.mul(S.mul(S.num(3.1415899999999999), S.getProperty(S.Value.Obj(this), "radius")), S.getProperty(S.Value.Obj(this), "radius"))
        return S.nil
    }
    
}

open class Shape : SageObject("Shape") {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun `init`(name: SageVal = S.nil): SageVal {
        S.setProperty(S.Value.Obj(this), "name", name)
        return S.nil
    }
    
    open fun describe(): SageVal {
        return S.add(S.str("Shape: "), S.getProperty(S.Value.Obj(this), "name"))
        return S.nil
    }
    
    open fun area(): SageVal {
        return S.num(0.0)
        return S.nil
    }
    
}

var c: S.Value = S.nil

fun main() {
    S.init()
    
    S.registerClass("Circle") { args -> S.Value.Obj(Circle().also { it.sageInit(*args) }) }
    S.registerClass("Shape") { args -> S.Value.Obj(Shape().also { it.sageInit(*args) }) }
    
    c = S.newInstance("Circle", S.num(5.0))
    S.printLn(S.callMethod(c, "describe"))
    S.printLn(S.callMethod(c, "area"))
    
}
