#include <stdint.h>
#include "metal_vm.h"

static void com1_putchar(char c) {
    // Write character to COM1 serial port
    __asm__ volatile ("outb %%al, %%dx" : : "a"(c), "d"((unsigned short)0x3F8));
}

// Minimal libc stubs for freestanding environment (64-bit)
void* memset(void* s, int c, unsigned long n) {
    unsigned char* p = (unsigned char*)s;
    while (n--) *p++ = (unsigned char)c;
    return s;
}

void* memcpy(void* dest, const void* src, unsigned long n) {
    unsigned char* d = (unsigned char*)dest;
    const unsigned char* s = (const unsigned char*)src;
    while (n--) *d++ = *s++;
    return dest;
}

unsigned long strlen(const char* s) {
    unsigned long n = 0;
    while (s[n]) n++;
    return n;
}

int strcmp(const char* s1, const char* s2) {
    while (*s1 && *s1 == *s2) { s1++; s2++; }
    return (int)(unsigned char)*s1 - (int)(unsigned char)*s2;
}

static void vm_write_char(char c) {
    com1_putchar(c);
}

// Symbols generated by objcopy for the kernel bytecode
extern unsigned char _binary_build_kernel_sgvm_start[];
extern unsigned char _binary_build_kernel_sgvm_end[];

static void print_string(const char* s) {
    while (*s) com1_putchar(*s++);
}

MetalVM g_vm;

void kmain(unsigned long handoff_ptr) {
    print_string("kmain: SageOS Kernel booting...\n");
    if (handoff_ptr) {
        unsigned long* magic_ptr = (unsigned long*)handoff_ptr;
        if (*magic_ptr == 0x534147454F534249ULL) {
            print_string("kmain: Booted via SageBoot!\n");
            unsigned long cmdline_ptr = *(unsigned long*)(handoff_ptr + 52);
            if (cmdline_ptr) {
                print_string("kmain: Boot cmdline: \"");
                print_string((const char*)cmdline_ptr);
                print_string("\"\n");
            }
        } else {
            print_string("kmain: Warning - invalid SageBoot handoff magic.\n");
        }
    } else {
        print_string("kmain: Warning - booted directly (no SageBoot metadata).\n");
    }

    metal_vm_init(&g_vm);
    g_vm.write_char = vm_write_char;

    unsigned char* start = _binary_build_kernel_sgvm_start;
    unsigned char* end = _binary_build_kernel_sgvm_end;
    int size = (int)(end - start);

    if (size > 0 && metal_vm_load_binary(&g_vm, start, size) == 0) {
        if (metal_vm_verify(&g_vm) == 0) {
            for (int i = 0; i < g_vm.chunk_count; i++) {
                metal_vm_load(&g_vm, g_vm.chunks[i], g_vm.chunk_lengths[i]);
                metal_vm_run(&g_vm);
            }
        }
    }

    while (1) {
        __asm__ volatile ("hlt");
    }
}
