#!/bin/bash
# ============================================================
#  SageLang Build Configuration (menuconfig)
#  Interactive TUI for configuring build options
#  Run: make menuconfig
# ============================================================

set -euo pipefail

CONFIG_FILE=".sage_config"

# --- Default values ---
CC="${CC:-gcc}"
BUILD_MODE="make"          # make or cmake
VULKAN="auto"              # auto, 1, 0
GLFW="auto"                # auto, 1, 0
DEBUG="0"                  # 0 or 1
OPTIMIZATION="-O2"         # -O0, -O1, -O2, -O3
PICO_BUILD="0"             # 0 or 1
INSTALL_PREFIX="/usr/local"
COMPILE_SHADERS="1"        # 0 or 1
RUN_TESTS="1"              # 0 or 1

# Load existing config
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

# --- TUI helpers ---
BOLD='\033[1m'
DIM='\033[2m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RESET='\033[0m'
REVERSE='\033[7m'

clear_screen() { printf '\033[2J\033[H'; }

draw_header() {
    clear_screen
    printf "${BOLD}${CYAN}"
    printf '%.0s═' $(seq 1 60)
    printf "\n  SageLang Build Configuration\n"
    printf '%.0s═' $(seq 1 60)
    printf "${RESET}\n\n"
}

draw_option() {
    local num="$1"
    local name="$2"
    local value="$3"
    local desc="$4"
    local color="${GREEN}"
    if [ "$value" = "0" ] || [ "$value" = "off" ]; then
        color="${RED}"
    elif [ "$value" = "auto" ]; then
        color="${YELLOW}"
    fi
    printf "  ${BOLD}%2s${RESET}) %-25s ${color}%-12s${RESET} ${DIM}%s${RESET}\n" "$num" "$name" "$value" "$desc"
}

draw_menu() {
    draw_header
    printf "  ${BOLD}Compiler & Build${RESET}\n"
    draw_option "1" "C Compiler" "$CC" "gcc, clang, cc"
    draw_option "2" "Build System" "$BUILD_MODE" "make or cmake"
    draw_option "3" "Optimization" "$OPTIMIZATION" "-O0 debug, -O2 release, -O3 aggressive"
    draw_option "4" "Debug Symbols" "$DEBUG" "Add -g -DDEBUG"
    printf "\n"
    printf "  ${BOLD}Features${RESET}\n"
    draw_option "5" "Vulkan GPU" "$VULKAN" "auto-detect, force on/off"
    draw_option "6" "GLFW Windowing" "$GLFW" "auto-detect, force on/off"
    draw_option "7" "Compile Shaders" "$COMPILE_SHADERS" "Build .spv from .glsl"
    printf "\n"
    printf "  ${BOLD}Platform${RESET}\n"
    draw_option "8" "Pico/RP2040 Build" "$PICO_BUILD" "Embedded target"
    draw_option "9" "Install Prefix" "$INSTALL_PREFIX" "make install destination"
    printf "\n"
    printf "  ${BOLD}Testing${RESET}\n"
    draw_option "10" "Run Tests" "$RUN_TESTS" "Run test suite after build"
    printf "\n"
    printf "  ${BOLD}Actions${RESET}\n"
    printf "  ${BOLD} s${RESET}) Save configuration\n"
    printf "  ${BOLD} b${RESET}) Save and build now\n"
    printf "  ${BOLD} q${RESET}) Quit without saving\n"
    printf "\n"
}

cycle_option() {
    local current="$1"
    shift
    local options=("$@")
    local next=0
    for i in "${!options[@]}"; do
        if [ "${options[$i]}" = "$current" ]; then
            next=$(( (i + 1) % ${#options[@]} ))
            break
        fi
    done
    echo "${options[$next]}"
}

save_config() {
    cat > "$CONFIG_FILE" << CFGEOF
# SageLang build configuration
# Generated by: make menuconfig
CC="$CC"
BUILD_MODE="$BUILD_MODE"
VULKAN="$VULKAN"
GLFW="$GLFW"
DEBUG="$DEBUG"
OPTIMIZATION="$OPTIMIZATION"
PICO_BUILD="$PICO_BUILD"
INSTALL_PREFIX="$INSTALL_PREFIX"
COMPILE_SHADERS="$COMPILE_SHADERS"
RUN_TESTS="$RUN_TESTS"
CFGEOF
    printf "\n  ${GREEN}Configuration saved to ${CONFIG_FILE}${RESET}\n"
    sleep 1
}

build_now() {
    save_config
    clear_screen
    printf "${BOLD}Building SageLang with saved configuration...${RESET}\n\n"

    local args=""
    if [ "$BUILD_MODE" = "make" ]; then
        args="--make-only"
    fi
    if [ "$RUN_TESTS" = "0" ]; then
        args="$args --skip-tests"
    fi

    # Export config as environment
    export CC
    if [ "$DEBUG" = "1" ]; then
        export DEBUG=1
    fi
    if [ "$VULKAN" != "auto" ]; then
        export VULKAN
    fi

    exec ./build.sh $args
}

# --- Main loop ---
while true; do
    draw_menu
    printf "  ${BOLD}Select option: ${RESET}"
    read -r choice

    case "$choice" in
        1)
            printf "  Enter compiler (gcc/clang/cc): "
            read -r val
            [ -n "$val" ] && CC="$val"
            ;;
        2)
            BUILD_MODE=$(cycle_option "$BUILD_MODE" "make" "cmake")
            ;;
        3)
            OPTIMIZATION=$(cycle_option "$OPTIMIZATION" "-O0" "-O1" "-O2" "-O3")
            ;;
        4)
            DEBUG=$(cycle_option "$DEBUG" "0" "1")
            ;;
        5)
            VULKAN=$(cycle_option "$VULKAN" "auto" "1" "0")
            ;;
        6)
            GLFW=$(cycle_option "$GLFW" "auto" "1" "0")
            ;;
        7)
            COMPILE_SHADERS=$(cycle_option "$COMPILE_SHADERS" "1" "0")
            ;;
        8)
            PICO_BUILD=$(cycle_option "$PICO_BUILD" "0" "1")
            ;;
        9)
            printf "  Enter install prefix [%s]: " "$INSTALL_PREFIX"
            read -r val
            [ -n "$val" ] && INSTALL_PREFIX="$val"
            ;;
        10)
            RUN_TESTS=$(cycle_option "$RUN_TESTS" "1" "0")
            ;;
        s|S)
            save_config
            ;;
        b|B)
            build_now
            ;;
        q|Q)
            printf "\n  ${DIM}Configuration not saved.${RESET}\n"
            exit 0
            ;;
        *)
            printf "  ${RED}Invalid option${RESET}\n"
            sleep 0.5
            ;;
    esac
done
