// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

var row: S.Value = S.nil
var matrix: S.Value = S.nil
var sliced: S.Value = S.nil
var items: S.Value = S.nil
var point: S.Value = S.nil
var person: S.Value = S.nil
var i: S.Value = S.nil
var n: S.Value = S.nil
var nums: S.Value = S.nil

fun main() {
    S.init()
    
    nums = S.array(S.num(10.0), S.num(20.0), S.num(30.0), S.num(40.0), S.num(50.0))
    S.printLn(nums)
    S.printLn(S.len(nums))
    S.printLn(S.index(nums, S.num(0.0)))
    S.printLn(S.index(nums, S.num(2.0)))
    S.push(nums, S.num(60.0))
    S.printLn(S.len(nums))
    run {
        val _iter_1 = S.toIterable(nums)
        for (n in _iter_1) {
            S.printLn(n)
        }
    }
    run {
        val _iter_2 = S.toIterable(S.range(S.num(5.0)))
        for (i in _iter_2) {
            S.printLn(i)
        }
    }
    run {
        val _iter_3 = S.toIterable(S.range(S.num(2.0), S.num(7.0)))
        for (i in _iter_3) {
            S.printLn(i)
        }
    }
    person = S.dict("name" to S.str("Alice"), "age" to S.num(30.0))
    S.printLn(person)
    S.printLn(S.dictKeys(person))
    S.printLn(S.dictValues(person))
    S.printLn(S.dictHas(person, S.str("name")))
    S.printLn(S.dictHas(person, S.str("email")))
    point = S.tuple(S.num(10.0), S.num(20.0), S.num(30.0))
    S.printLn(point)
    S.printLn(S.index(point, S.num(0.0)))
    S.printLn(S.len(point))
    items = S.array(S.num(1.0), S.num(2.0), S.num(3.0), S.num(4.0), S.num(5.0))
    sliced = S.slice(items, S.num(1.0), S.num(3.0))
    S.printLn(sliced)
    matrix = S.array(S.array(S.num(1.0), S.num(2.0)), S.array(S.num(3.0), S.num(4.0)), S.array(S.num(5.0), S.num(6.0)))
    run {
        val _iter_4 = S.toIterable(matrix)
        for (row in _iter_4) {
            S.printLn(row)
        }
    }
    
}
