// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

open class Cat : Animal() {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun speak(): SageVal {
        return S.add(S.getProperty(SageRuntime.Value.Obj(this), "name"), S.str(" meows!"))
        return S.nil
    }
    
}

open class Dog : Animal() {
    override val props = mutableMapOf<String, SageVal>()
    
    open fun speak(): SageVal {
        return S.add(S.getProperty(SageRuntime.Value.Obj(this), "name"), S.str(" barks!"))
        return S.nil
    }
    
}

open class Animal : SageObject("Animal") {
    override val props = mutableMapOf<String, SageVal>()
    
    override fun sageInit(vararg args: SageVal): SageVal {
        val name: SageVal = if (args.size > 0) args[0] else S.nil
        S.setProperty(SageRuntime.Value.Obj(this), "name", name)
        return S.nil
    }
    
    open fun speak(): SageVal {
        return S.add(S.getProperty(SageRuntime.Value.Obj(this), "name"), S.str(" makes a sound"))
        return S.nil
    }
    
    open fun describe(): SageVal {
        return S.add(S.str("I am "), S.getProperty(SageRuntime.Value.Obj(this), "name"))
        return S.nil
    }
    
}

var e: S.Value = S.nil
var animal: S.Value = S.nil
var cat: S.Value = S.nil
var dog: S.Value = S.nil

fun main() {
    S.init()
    
    S.registerClass("Cat") { args -> Cat().also { it.sageInit(*args) } }
    S.registerClass("Dog") { args -> Dog().also { it.sageInit(*args) } }
    S.registerClass("Animal") { args -> Animal().also { it.sageInit(*args) } }
    
    dog = S.newInstance("Dog", S.str("Rex"))
    cat = S.newInstance("Cat", S.str("Whiskers"))
    S.printLn(S.callMethod(dog, "speak"))
    S.printLn(S.callMethod(cat, "speak"))
    S.printLn(S.callMethod(dog, "describe"))
    animal = S.str("dog")
    run {
        val _match_1 = animal
        if (S.equal(_match_1, S.str("dog"))) {
            S.printLn(S.str("It's a dog"))
        } else if (S.equal(_match_1, S.str("cat"))) {
            S.printLn(S.str("It's a cat"))
        } else {
            S.printLn(S.str("Unknown animal"))
        }
    }
    try {
        throw SageException(S.str("Something went wrong"))
    } catch (_e: SageException) {
        var e = _e.value
        S.printLn(S.add(S.str("Caught: "), e))
    } finally {
        S.printLn(S.str("Cleanup done"))
    }
    
}
