// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = SageRuntime.Value

fun main() {
    S.init()
    
    var x: Double = 10.0
    var y: Double = 20.0
    var sum = S.add(S.num(x), S.num(y))
    S.printLn(sum)
    var result = S.add(S.mul(S.num(x), S.num(y)), S.num(5.0))
    S.printLn(result)
    var total: Double = 0.0
    var i: Double = 0.0
    while (S.truthy(S.lt(S.num(i), S.num(100.0)))) {
        total = S.add(S.num(total), S.num(i))
        i = S.add(S.num(i), S.num(1.0))
    }
    S.printLn(S.num(total))
    
}
