// Generated by Sage Kotlin Backend
// https://github.com/sageLang/sage
@file:Suppress("UNUSED_PARAMETER", "UNUSED_VARIABLE", "NAME_SHADOWING")

import sage.runtime.*
import sage.runtime.SageRuntime as S
import kotlinx.coroutines.*

typealias SageVal = S.Value

fun count_up(n: SageVal): Sequence<SageVal> = sequence {
    var i = S.num(0.0)
    while (S.truthy(S.lt(i, n))) {
        yield(i)
        i = S.add(i, S.num(1.0))
    }
}

fun fibonacci_gen(): Sequence<SageVal> = sequence {
    var a = S.num(0.0)
    var b = S.num(1.0)
    while (S.truthy(S.bool(true))) {
        yield(a)
        var temp = S.add(a, b)
        a = b
        b = temp
    }
}

var x: S.Value = S.nil

fun main() {
    S.init()
    
    run {
        val _iter_1 = S.toIterable(count_up(S.num(5.0)))
        for (x in _iter_1) {
            S.printLn(x)
        }
    }
    
}
