# SageLang assembly output for x86_64
# Profile: baremetal
# Generated by sage compiler

.text
.globl sage_entry

sage_entry:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
  # call gc_disable
  call sage_fn_gc_disable
  movq %rax, -16(%rbp)
  movq %rdx, -8(%rbp)
  # v1 = string
  leaq .LC0(%rip), %rdi
  call sage_rt_string
  movq %rax, -32(%rbp)
  movq %rdx, -24(%rbp)
  # store global 'KERNEL_NAME' = v1
  leaq sage_globals(%rip), %rdi
  leaq .LC1(%rip), %rsi
  movq -32(%rbp), %rdx
  movq -24(%rbp), %rcx
  call sage_rt_set_global
  # v2 = string
  leaq .LC2(%rip), %rdi
  call sage_rt_string
  movq %rax, -48(%rbp)
  movq %rdx, -40(%rbp)
  # store global 'KERNEL_VERSION' = v2
  leaq sage_globals(%rip), %rdi
  leaq .LC3(%rip), %rsi
  movq -48(%rbp), %rdx
  movq -40(%rbp), %rcx
  call sage_rt_set_global
  # v3 = nil
  call sage_rt_nil
  movq %rax, -64(%rbp)
  movq %rdx, -56(%rbp)
  # v4 = nil
  call sage_rt_nil
  movq %rax, -80(%rbp)
  movq %rdx, -72(%rbp)
  # v5 = nil
  call sage_rt_nil
  movq %rax, -96(%rbp)
  movq %rdx, -88(%rbp)
  # v6 = nil
  call sage_rt_nil
  movq %rax, -112(%rbp)
  movq %rdx, -104(%rbp)
  # v7 = nil
  call sage_rt_nil
  movq %rax, -128(%rbp)
  movq %rdx, -120(%rbp)
  # v8 = nil
  call sage_rt_nil
  movq %rax, -144(%rbp)
  movq %rdx, -136(%rbp)
  # v9 = nil
  call sage_rt_nil
  movq %rax, -160(%rbp)
  movq %rdx, -152(%rbp)
  # v10 = nil
  call sage_rt_nil
  movq %rax, -176(%rbp)
  movq %rdx, -168(%rbp)
  # v11 = nil
  call sage_rt_nil
  movq %rax, -192(%rbp)
  movq %rdx, -184(%rbp)
  # v12 = nil
  call sage_rt_nil
  movq %rax, -208(%rbp)
  movq %rdx, -200(%rbp)
  # v13 = nil
  call sage_rt_nil
  movq %rax, -224(%rbp)
  movq %rdx, -216(%rbp)
  # v14 = nil
  call sage_rt_nil
  movq %rax, -240(%rbp)
  movq %rdx, -232(%rbp)
  # call kmain
  call sage_fn_kmain
  movq %rax, -256(%rbp)
  movq %rdx, -248(%rbp)
  xorl %eax, %eax
  leave
  ret

.section .rodata
.LC0:
  .asciz "SageOS"
.LC1:
  .asciz "KERNEL_NAME"
.LC2:
  .asciz "0.1.0"
.LC3:
  .asciz "KERNEL_VERSION"
