#!/bin/bash
# Convert SageLLM model to GGUF for llama.cpp
# Generated by SageLLM

MODEL_NAME="sage-tiny"
WEIGHTS="models/export/sage-tiny.gguf"
OUTPUT="models/export/sage-tiny.gguf"

echo "Converting $MODEL_NAME to GGUF..."

# Architecture info
echo "  Layers: 2"
echo "  d_model: 64"
echo "  Heads: 2"
echo "  Context: 128"
echo "  Vocab: 256"

# Quantization options
# Q4_0: fastest, smallest (4-bit)
# Q5_1: balanced quality/size
# Q8_0: highest quality quantized
# F16: full precision (largest)

QUANT=${1:-Q4_0}

if command -v llama-quantize &> /dev/null; then
    echo "Quantizing to $QUANT..."
    llama-quantize $OUTPUT ${OUTPUT%.gguf}-${QUANT}.gguf $QUANT
    echo "Done: ${OUTPUT%.gguf}-${QUANT}.gguf"
else
    echo "llama-quantize not found. Install llama.cpp first."
    echo "  git clone https://github.com/ggerganov/llama.cpp"
    echo "  cd llama.cpp && make"
fi

# Load into Ollama
if command -v ollama &> /dev/null; then
    echo "Creating Ollama model..."
    ollama create $MODEL_NAME -f Modelfile
    echo "Run: ollama run $MODEL_NAME"
fi
